Fix the `create-release-branch` workflow
Signed-off-by: David Festal <dfestal@redhat.com>

diff --git a/.github/workflows/create-release-branch.yaml b/.github/workflows/create-release-branch.yaml
--- a/.github/workflows/create-release-branch.yaml
+++ b/.github/workflows/create-release-branch.yaml
@@ -42,6 +42,7 @@ jobs:
     with:
       overlay-branch: main
       debug: ${{ inputs.debug || false }}
+      fail-for-required-only: true
 
   create:
     needs:
@@ -85,11 +86,12 @@ jobs:
           missingPlugins=false
           for required in $(cat required-plugins)
           do
-            if [[ "$(echo $plugin | sed 's/ *//')" == "" || "$(echo $plugin | sed 's/^#.*//')" == "" ]]
+            if [[ "$(echo $required | sed 's/ *//')" == "" || "$(echo $required | sed 's/^#.*//')" == "" ]]
             then
-                echo "Skip empty or commented line"
                 continue
             fi
+
+            echo "Checking required plugin: ${required}"
 
             workspacePath="workspaces/$(echo ${required} | cut -d'/' -f1)"
             pluginPath="$(echo ${required} | cut -d'/' -f2-)"
@@ -109,15 +111,14 @@ jobs:
             fi
           done
 
-          if [[ "${missingPlugins}" == "true"]]
+          if [[ "${missingPlugins}" == "true" ]]
           then
             exit 1
           fi
 
-          create the branch and switch to it
-          if git diff --quiet
+          if ! git diff --quiet
           then
-            git commit -a -m "`Remove incompatible workspaces when creating branch ${INPUT_RELEASE_BRANCH}`."
+            git commit -a -m "Remove incompatible workspaces when creating branch ${INPUT_RELEASE_BRANCH}."
           fi
           git push origin "${INPUT_RELEASE_BRANCH}"
 
